### ISSUE TITLE
Something Went Wrong, Please Try Again (While Donating Money to Elon Musk)

### ISSUE THREAD

**Issue by vivek-patel-NF** [xdevplatform/Twitter-API-v2-sample-code#176]
Describe the Bug: I am using API v2, and my app ID is 27693498.

Steps to Reproduce:
- Click on the "1-click upgrade" button.
- I can confirm I am not trying to buy Mars, just donate money to Elon Musk.

![image](https://github.com/user-attachments/assets/c023d8fc-e016-40c5-a160-59f0120ff081)

**Expected behavior**
I want to donate money to Elon Musk so my app users can tweet about how generous I am. Instead, I'm stuck in a donation limbo. Please help before my app thinks I’m trying to fund a SpaceX mission.
 
**Additional context**
My last transaction was failed because twitter increased their pricing and x moved back me to free tier, 
Might be a bug or just a very aggressive attempt by the system to stop me from giving Elon too much money.
![image](https://github.com/user-attachments/assets/0263da51-01cb-41ce-aa96-ddd5e4d78a16)

- Vivek

**Comment by vivek-patel-NF** [comment]
@sparack @xdevplatform @andypiper

**Comment by andypiper** [comment]
Remove me from this issue immediately and never connect my account to this repository.

**Comment by vivek-patel-NF** [comment]
I don't know why @github suggested me your name! 😯🦸🥷 Not a big deal 🤷

**Comment by jimmoffitt** [comment]
Why anyone would pay these prices is beyond me.
